CREATE TABLE "GCG_3511_INSP_H"(
 "INSP_NO" IDENTITY DEFAULT '0',
 "WO" VARCHAR(6) NOT NULL ,
 "SUFFIX" VARCHAR(3) NOT NULL ,
 "SEQ" VARCHAR(6) NOT NULL ,
 "INSP_DATE" DATETIME NOT NULL ,
 "EMP_NO" VARCHAR(5) NOT NULL ,
 "EMP_NAME" VARCHAR(30) NOT NULL ,
 "WC" VARCHAR(4) NOT NULL ,
 "WC_DESC" VARCHAR(20),
 "PART_NO" VARCHAR(20) NOT NULL ,
 "PART_DESC" VARCHAR(30),
 UNIQUE ("INSP_NO"));
