CREATE TABLE "GCG_3511_INSP_L"(
 "INSP_NO" INTEGER NOT NULL ,
 "SEQ" INTEGER NOT NULL ,
 "SAMPLE_ID" VARCHAR(2) NOT NULL ,
 "TYPE_LOC" VARCHAR(10) NOT NULL ,
 "REQ_DIM" DOUBLE NOT NULL ,
 "TOL" DOUBLE NOT NULL ,
 "ACT_DIM" DOUBLE NOT NULL ,
 "GAUGE" INTEGER NOT NULL ,
 "ACPT_REJ" VARCHAR(1) NOT NULL ,
 "NOTES" VARCHAR(50));
